server:
  port: 8888
spring:
  application:
    name: Config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MikaelGG/ShoppingCartBold
          default-label: main
          search-paths: Data-config



